stages:
  - lint
  - test

lint:
  stage: lint
  image: python:3.13
  before_script:
    - python -m pip install --upgrade pip
    - pip install uv rust-just
  script:
    - just lint

test:
  stage: test
  image: python:${PYTHON_VERSION}
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.11", "3.12", "3.13"]
  before_script:
    - python -m pip install --upgrade pip
    - pip install uv rust-just
  script:
    - just cov
  artifacts:
    paths:
      - coverage.xml
